var GAME_LEVELS = [
  ["                              vvvvvvvv                                          ",
   "                            v         v                                            ",
   "                          v            v                                          ",
   "                        v                v                                        ",
   "                      v                   v                                       ",
   "                    v                      v                                      ",
   "                  v                         v                                    ",
   "                v                            v                                   ",
   "              v                               v                                    ",
   "            v                                  v                                ",
   "          v                                     v                                ",
   "        v                                        v                                ",
   "  x                                               v                             ",
   "  x                                                v                            ",
   "  x                                                 v                        ",
   "  x                 o                                v                         ",
   "  x  @                            o                   v                         ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      xxxxxxxxxxxxxxxxxxxxx",
   "                              x   x!!!!!!!!!!!!!!!!!!!!!                  x     x                    ",
   "                              x!!!x!!!!!!!!!!!!!!!!!!!!                 x!!!!!x                    ",
   "                              x!!!x!!!!!!!!!!!!!!!!!!!!!!                  x!!!!!x                    ",
   "                              xxxxx!!!!!!!!!!!!!!!!!!!!!!!                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                                                                      ",
   "                                      x!!xo                                                                      ",
   "                                      x!!xxxxxxxxxxx=                o                                          ",
   "                                      xx!!!!!!!!!!x!   x!xx!xx!xx!xxxx!xx!xx!xx!xx!xx!xx!xx!xx!xx!xx!xx!xx!xx!   ",
   "                                       xxxxxxxxxx!!xx                                                    vvvvvvv           ",
   "                                                xx!x!o                                                             ",
   "                                                 x!xxxx                                                             ",
   "                                                 xvx   xxxxxxxxxxxxxxxxx                                                     ",
   "                                                            vxxxxxxxxxxxxxxxxxxxx                                  ",
   "                                                                                          xxx                  ",
   "                                                  x                                     xxx      o                ",
   "                                    v        v      v                o                xxx      xxx                       ",
   "                                                                                   xx                               ",
   "                                                              o                   xx                             ",
   "                                                         o              xxxxxxxxxxxxx                                      ",
   "                                                o                xxx                                               ", 
   "                                                                                                              ",
   "               xxxxxxxxxxxx                               xxx                                                 ",
   "              xx!!!!!!!!!!xx                         xxx                                                           ",
   "             xx!!!!!!!!!!!!xx               xxx                                                                          ",
   "     @       x!!!!!!!!!!!!!xx      xxx                                                                                 ",
   "    xxx=o   =x!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                       ",
   "    x xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                      ",
   "!!!!x x!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     ",
   "!!!!x x!!!!!!x                                                                                                    ",
   "!!!!x x!!!!!!x                                                                                                    ",
   "!!!!x x!!!!!!x                                                                                                    ",
   "!!!!x x!!!!!!x                                                                                                    ",
   "!!!!x x!!!!!!x                                                                                                    ",
   "!!!!x x!!!!!!x                                                                               "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                             ",
   "                                        @                                                                      ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                                                 ",
   "                                       x x                                                    ",
   "                                     xxx xxx                                                  ",
   "                                      x   x                                                 ",
   "                                      x   x                                               ",
   "                                      x   x                                                  ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                              ",
   "                                          x           x                    x!!!x                              ",
   "  x                                   o   x           x                     xxx                               ",
   "  x                                   xx   xx          x                              o                       ",
   "  x                                    x   x           x            xxx                                        ",
   "  x                                    x   x           x           x!!!x                                       ",
   "  x                                 x  x   x           x     o      xxx                                     ",
   "  x                                    x   xx          x                                                     x   ",
   "  x                            o   o  xx   x           x     x                          ||||||||||||		 x ",
   "  x                                    x   x                xxxxxxxxxxxx                                     x      ",
   "  x                           xxx xxx xxx xxx     o o  xx!!!!!!!!!!!!!!x                                     x ",
   "  x                           x xxx                 xxxxxxx!!!!!!!!!!!!!!x                                   x     ",
   "  x                           x =                xxxxxxxxxxxxxxxxxxxxxxx                                     x  ",
   "  x                           xx     x   x  xx                                         xxx                   x   ",
   "  xxx                         x           x                                         x!!!x                  xxx  ",
   "  x x                         x           x                        xxxxxxxx    xxx                 x         x  ",
   "  x                           x    x    xxxxxxx                        xxxxx    x                            x  ",
   "  x                           x|          x                              x   x      x          x             x  ",
   "  x                          oxx      x                                  x x x  x         x                  x  ",
   "  x                          xx                                            x        x    o   x                x  ",
   "  x                                   o  xx                                    x  x      x                    x  ",
   "  x                             xx    xx    x                                             x                 x  ",
   "  x                      xxx    xxx!!!!!!x=      o        =xx=     o           x x x x                     x  ",
   "  x                xxx        xxxxxxxxxxxxx  xxxxxx    xxxxxx     xxxx   xxxxxx                              x  ",
   "  x                x         x           x!!x!!!!x!!!!x!!!!!x!!!!x!!!!!!xx=======                         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                         ",
   "                                                                                                             ",
   "                                                                                                         ",
   "                                                                                                             ",
   "                                                                                                        ",
   "                                                                                                        ",
   "                                                                                                   ",
   "              																									            ",
   "           																								  ",
   "           																													    ",
   "           				x																						  ",
   "             																												",
   "                                                       														 ",
   "                                                                                                              ",
   "                                          																                 ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                         ",
   "                        x       x        	x		x	x	xx		x					                         ",
   "                        x       x           x       x       x x     x                                               ",
   "                        x       x    		x	x	x	x	x	x	x							            ",
   "                        x       x           x   x   x   x   x    x  x                                         ",
   "                        x   	x			x	x	x	x	x	  x	x								  ",
   "                        xxxxxxxxx           xxxxxxxxx   x   x       x                                                             ",
   "                                                                                                            ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x                        																					   ",
   "  x                          																							   ",
   "  x  @                                                                                                          ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
